# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'moveCircleColor' do
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxOptional'

  # Pods for moveCircleColor

end
